# This workflow enables developers to call PR-Actions `/[actions]` in PR's comments and upon PR creation. 
# Learn more at https://www.khulnasoft.com/pr-action/
# This is v0.2 of this workflow file

name: PR-Action

on:
# pull_request:
# issue_comment:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_action_job:
    runs-on: ubuntu-latest
    name: Run pr action on every pull request
    steps:
      - name: PR Action action step
        id: praction
        uses: Khulnasoft/pr-action@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }} # optional
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINECONE.API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE.ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true



